
list(APPEND c
	code/ai/ai.cpp
	code/ai/ai.h
	code/ai/ai_profiles.cpp
	code/ai/ai_profiles.h
	code/ai/aibig.cpp
	code/ai/aibig.h
	code/ai/aicode.cpp
	code/ai/aigoals.cpp
	code/ai/aigoals.h
	code/ai/aiinternal.h
	code/ai/ailocal.h
	code/ai/aiturret.cpp
	code/anim/animplay.cpp
	code/anim/animplay.h
	code/anim/packunpack.cpp
	code/anim/packunpack.h	
	code/asteroid/asteroid.cpp
	code/asteroid/asteroid.h
	code/autopilot/autopilot.cpp
	code/autopilot/autopilot.h
	code/bmpman/bm_internal.h
	code/bmpman/bmpman.cpp
	code/bmpman/bmpman.h
	code/camera/camera.cpp
	code/camera/camera.h
	code/cfile/cfile.cpp
	code/cfile/cfile.h
	code/cfile/cfilearchive.cpp
	code/cfile/cfilearchive.h
	code/cfile/cfilelist.cpp
	code/cfile/cfilesystem.cpp
	code/cfile/cfilesystem.h
	code/cmdline/cmdline.cpp
	code/cmdline/cmdline.h
	code/cmeasure/cmeasure.cpp
	code/cmeasure/cmeasure.h
	code/controlconfig/controlsconfig.cpp
	code/controlconfig/controlsconfig.h
	code/controlconfig/controlsconfigcommon.cpp
	code/cutscene/cutscenes.cpp
	code/cutscene/cutscenes.h
	code/cutscene/decoder16.cpp
	code/cutscene/decoder8.cpp
	code/cutscene/movie.cpp
	code/cutscene/movie.h
	code/cutscene/mve_audio.cpp
	code/cutscene/mvelib.cpp
	code/cutscene/mvelib.h
	code/cutscene/mveplayer.cpp
	code/cutscene/oggplayer.cpp
	code/cutscene/oggplayer.h
	code/ddsutils/ddsutils.cpp
	code/ddsutils/ddsutils.h
	code/debris/debris.cpp
	code/debris/debris.h
	code/debugconsole/console.cpp
	code/debugconsole/timerbar.cpp
	code/debugconsole/timerbar.h
	code/exceptionhandler/exceptionhandler.cpp
	code/exceptionhandler/exceptionhandler.h
	code/external_dll/externalcode.h
	code/external_dll/trackirglobal.cpp
	code/external_dll/trackirpublic.h
	code/fireball/fireballs.cpp
	code/fireball/fireballs.h
	code/fireball/warpineffect.cpp
	code/fs2netd/fs2netd_client.cpp
	code/fs2netd/fs2netd_client.h
	code/fs2netd/protocol.h
	code/fs2netd/tcp_client.cpp
	code/fs2netd/tcp_client.h
	code/fs2netd/tcp_socket.cpp
	code/fs2netd/tcp_socket.h
	code/gamehelp/contexthelp.cpp
	code/gamehelp/contexthelp.h
	code/gamehelp/gameplayhelp.cpp
	code/gamehelp/gameplayhelp.h
	code/gamesequence/gamesequence.cpp
	code/gamesequence/gamesequence.h
	code/gamesnd/eventmusic.cpp
	code/gamesnd/eventmusic.h
	code/gamesnd/gamesnd.cpp
	code/gamesnd/gamesnd.h
	code/globalincs/alphacolors.cpp
	code/globalincs/alphacolors.h
	code/globalincs/def_files.cpp
	code/globalincs/def_files.h
	code/globalincs/globals.h
	code/globalincs/linklist.h
	code/globalincs/profiling.cpp
	code/globalincs/pstypes.h
	code/globalincs/safe_strings.cpp
	code/globalincs/safe_strings.h
	code/globalincs/safe_strings_test.cpp
	code/globalincs/systemvars.cpp
	code/globalincs/systemvars.h
	code/globalincs/version.cpp
	code/globalincs/version.h
	code/graphics/2d.cpp
	code/graphics/2d.h
	code/graphics/font.cpp
	code/graphics/font.h
	code/graphics/generic.cpp
	code/graphics/generic.h
	code/graphics/grbatch.cpp
	code/graphics/grbatch.h
	code/graphics/grinternal.h
	code/graphics/gropengl.cpp
	code/graphics/gropengl.h
	code/graphics/gropenglbmpman.cpp
	code/graphics/gropenglbmpman.h
	code/graphics/gropengldraw.cpp
	code/graphics/gropengldraw.h
	code/graphics/gropenglextension.cpp
	code/graphics/gropenglextension.h
	code/graphics/gropengllight.cpp
	code/graphics/gropengllight.h
	code/graphics/gropenglpostprocessing.cpp
	code/graphics/gropenglpostprocessing.h
	code/graphics/gropenglshader.cpp
	code/graphics/gropenglshader.h
	code/graphics/gropenglstate.cpp
	code/graphics/gropenglstate.h
	code/graphics/gropengltexture.cpp
	code/graphics/gropengltexture.h
	code/graphics/gropengltnl.cpp
	code/graphics/gropengltnl.h
	code/graphics/grstub.cpp
	code/graphics/grstub.h
	code/graphics/line.h
	code/graphics/tmapper.h
	code/hud/hud.cpp
	code/hud/hud.h
	code/hud/hudartillery.cpp
	code/hud/hudartillery.h
	code/hud/hudbrackets.cpp
	code/hud/hudbrackets.h
	code/hud/hudconfig.cpp
	code/hud/hudconfig.h
	code/hud/hudescort.cpp
	code/hud/hudescort.h
	code/hud/hudets.cpp
	code/hud/hudets.h
	code/hud/hudgauges.h
	code/hud/hudlock.cpp
	code/hud/hudlock.h
	code/hud/hudmessage.cpp
	code/hud/hudmessage.h
	code/hud/hudnavigation.cpp
	code/hud/hudnavigation.h
	code/hud/hudobserver.cpp
	code/hud/hudobserver.h
	code/hud/hudparse.cpp
	code/hud/hudparse.h
	code/hud/hudreticle.cpp
	code/hud/hudreticle.h
	code/hud/hudshield.cpp
	code/hud/hudshield.h
	code/hud/hudsquadmsg.cpp
	code/hud/hudsquadmsg.h
	code/hud/hudtarget.cpp
	code/hud/hudtarget.h
	code/hud/hudtargetbox.cpp
	code/hud/hudtargetbox.h
	code/hud/hudwingmanstatus.cpp
	code/hud/hudwingmanstatus.h
	code/iff_defs/iff_defs.cpp
	code/iff_defs/iff_defs.h
	code/inetfile/cftp.cpp
	code/inetfile/cftp.h
	code/inetfile/chttpget.cpp
	code/inetfile/chttpget.h
	code/inetfile/inetgetfile.cpp
	code/inetfile/inetgetfile.h
	code/io/key.cpp
	code/io/key.h
	code/io/keycontrol.cpp
	code/io/keycontrol.h
	code/io/mouse.cpp
	code/io/mouse.h
	code/io/timer.cpp
	code/io/timer.h
	code/jpgutils/jpgutils.cpp
	code/jpgutils/jpgutils.h
	code/jumpnode/jumpnode.cpp
	code/jumpnode/jumpnode.h
	code/lighting/lighting.cpp
	code/lighting/lighting.h
	code/localization/fhash.cpp
	code/localization/fhash.h
	code/localization/localize.cpp
	code/localization/localize.h
	code/math/fix.cpp
	code/math/fix.h
	code/math/floating.cpp
	code/math/floating.h
	code/math/fvi.cpp
	code/math/fvi.h
	code/math/spline.cpp
	code/math/spline.h
	code/math/staticrand.cpp
	code/math/staticrand.h
	code/math/vecmat.cpp
	code/math/vecmat.h
	code/menuui/barracks.cpp
	code/menuui/barracks.h
	code/menuui/credits.cpp
	code/menuui/credits.h
	code/menuui/fishtank.cpp
	code/menuui/fishtank.h
	code/menuui/mainhallmenu.cpp
	code/menuui/mainhallmenu.h
	code/menuui/mainhalltemp.cpp
	code/menuui/mainhalltemp.h
	code/menuui/optionsmenu.cpp
	code/menuui/optionsmenu.h
	code/menuui/optionsmenumulti.cpp
	code/menuui/optionsmenumulti.h
	code/menuui/playermenu.cpp
	code/menuui/playermenu.h
	code/menuui/readyroom.cpp
	code/menuui/readyroom.h
	code/menuui/snazzyui.cpp
	code/menuui/snazzyui.h
	code/menuui/techmenu.cpp
	code/menuui/techmenu.h
	code/menuui/trainingmenu.cpp
	code/menuui/trainingmenu.h
	code/mission/missionbriefcommon.cpp
	code/mission/missionbriefcommon.h
	code/mission/missioncampaign.cpp
	code/mission/missioncampaign.h
	code/mission/missiongoals.cpp
	code/mission/missiongoals.h
	code/mission/missiongrid.cpp
	code/mission/missiongrid.h
	code/mission/missionhotkey.cpp
	code/mission/missionhotkey.h
	code/mission/missionload.cpp
	code/mission/missionload.h
	code/mission/missionlog.cpp
	code/mission/missionlog.h
	code/mission/missionmessage.cpp
	code/mission/missionmessage.h
	code/mission/missionparse.cpp
	code/mission/missionparse.h
	code/mission/missiontraining.cpp
	code/mission/missiontraining.h
	code/missionui/chatbox.cpp
	code/missionui/chatbox.h
	code/missionui/fictionviewer.cpp
	code/missionui/fictionviewer.h
	code/missionui/missionbrief.cpp
	code/missionui/missionbrief.h
	code/missionui/missioncmdbrief.cpp
	code/missionui/missioncmdbrief.h
	code/missionui/missiondebrief.cpp
	code/missionui/missiondebrief.h
	code/missionui/missionloopbrief.cpp
	code/missionui/missionloopbrief.h
	code/missionui/missionpause.cpp
	code/missionui/missionpause.h
	code/missionui/missionrecommend.cpp
	code/missionui/missionrecommend.h
	code/missionui/missionscreencommon.cpp
	code/missionui/missionscreencommon.h
	code/missionui/missionshipchoice.cpp
	code/missionui/missionshipchoice.h
	code/missionui/missionstats.cpp
	code/missionui/missionstats.h
	code/missionui/missionweaponchoice.cpp
	code/missionui/missionweaponchoice.h
	code/missionui/redalert.cpp
	code/missionui/redalert.h
	code/mod_table/mod_table.cpp
	code/mod_table/mod_table.h
	code/model/model.h
	code/model/modelanim.cpp
	code/model/modelanim.h
	code/model/modelcollide.cpp
	code/model/modelinterp.cpp
	code/model/modeloctant.cpp
	code/model/modelread.cpp
	code/model/modelsinc.h
	code/nebula/neb.cpp
	code/nebula/neb.h
	code/nebula/neblightning.cpp
	code/nebula/neblightning.h
	code/network/chat_api.cpp
	code/network/chat_api.h
	code/network/multi.cpp
	code/network/multi.h
	code/network/multi_campaign.cpp
	code/network/multi_campaign.h
	code/network/multi_data.cpp
	code/network/multi_data.h
	code/network/multi_dogfight.cpp
	code/network/multi_dogfight.h
	code/network/multi_endgame.cpp
	code/network/multi_endgame.h
	code/network/multi_ingame.cpp
	code/network/multi_ingame.h
	code/network/multi_kick.cpp
	code/network/multi_kick.h
	code/network/multi_log.cpp
	code/network/multi_log.h
	code/network/multi_obj.cpp
	code/network/multi_obj.h
	code/network/multi_observer.cpp
	code/network/multi_observer.h
	code/network/multi_options.cpp
	code/network/multi_options.h
	code/network/multi_pause.cpp
	code/network/multi_pause.h
	code/network/multi_pinfo.cpp
	code/network/multi_pinfo.h
	code/network/multi_ping.cpp
	code/network/multi_ping.h
	code/network/multi_pmsg.cpp
	code/network/multi_pmsg.h
	code/network/multi_pxo.cpp
	code/network/multi_pxo.h
	code/network/multi_rate.cpp
	code/network/multi_rate.h
	code/network/multi_respawn.cpp
	code/network/multi_respawn.h
	code/network/multi_sexp.cpp
	code/network/multi_sexp.h
	code/network/multi_team.cpp
	code/network/multi_team.h
	code/network/multi_update.h
	code/network/multi_voice.cpp
	code/network/multi_voice.h
	code/network/multi_xfer.cpp
	code/network/multi_xfer.h
	code/network/multilag.cpp
	code/network/multilag.h
	code/network/multimsgs.cpp
	code/network/multimsgs.h
	code/network/multiteamselect.cpp
	code/network/multiteamselect.h
	code/network/multiui.cpp
	code/network/multiui.h
	code/network/multiutil.cpp
	code/network/multiutil.h
	code/network/psnet2.cpp
	code/network/psnet2.h
	code/network/stand_gui-unix.cpp
	code/network/stand_gui.cpp
	code/network/stand_gui.h
	code/object/collidedebrisship.cpp
	code/object/collidedebrisweapon.cpp
	code/object/collideshipship.cpp
	code/object/collideshipweapon.cpp
	code/object/collideweaponweapon.cpp
	code/object/deadobjectdock.cpp
	code/object/deadobjectdock.h
	code/object/objcollide.cpp
	code/object/objcollide.h
	code/object/object.cpp
	code/object/object.h
	code/object/objectdock.cpp
	code/object/objectdock.h
	code/object/objectshield.cpp
	code/object/objectshield.h
	code/object/objectsnd.cpp
	code/object/objectsnd.h
	code/object/objectsort.cpp
	code/object/parseobjectdock.cpp
	code/object/parseobjectdock.h
	code/object/waypoint.cpp
	code/object/waypoint.h
	code/observer/observer.cpp
	code/observer/observer.h
	code/palman/palman.cpp
	code/palman/palman.h
	code/parse/encrypt.cpp
	code/parse/encrypt.h
	code/parse/generic_log.cpp
	code/parse/generic_log.h
	code/parse/lua.cpp
	code/parse/lua.h
	code/parse/parselo.cpp
	code/parse/parselo.h
	code/parse/scripting.cpp
	code/parse/scripting.h
	code/parse/sexp.cpp
	code/parse/sexp.h
	code/particle/particle.cpp
	code/particle/particle.h
	code/pcxutils/pcxutils.cpp
	code/pcxutils/pcxutils.h
	code/physics/physics.cpp
	code/physics/physics.h
	code/pilotfile/csg.cpp
	code/pilotfile/csg_convert.cpp
	code/pilotfile/pilotfile.cpp
	code/pilotfile/pilotfile.h
	code/pilotfile/pilotfile_convert.cpp
	code/pilotfile/pilotfile_convert.h
	code/pilotfile/plr.cpp
	code/pilotfile/plr_convert.cpp
	code/playerman/managepilot.cpp
	code/playerman/managepilot.h
	code/playerman/player.h
	code/playerman/playercontrol.cpp
	code/pngutils/pngutils.cpp
	code/pngutils/pngutils.h
	code/popup/popup.cpp
	code/popup/popup.h
	code/popup/popupdead.cpp
	code/popup/popupdead.h
	code/radar/radar.cpp
	code/radar/radar.h
	code/radar/radardradis.cpp
	code/radar/radardradis.h
	code/radar/radarorb.cpp
	code/radar/radarorb.h
	code/radar/radarsetup.cpp
	code/radar/radarsetup.h
	code/render/3d.h
	code/render/3dclipper.cpp
	code/render/3ddraw.cpp
	code/render/3dinternal.h
	code/render/3dlaser.cpp
	code/render/3dmath.cpp
	code/render/3dsetup.cpp
	code/ship/afterburner.cpp
	code/ship/afterburner.h
	code/ship/awacs.cpp
	code/ship/awacs.h
	code/ship/shield.cpp
	code/ship/ship.cpp
	code/ship/ship.h
	code/ship/shipcontrails.cpp
	code/ship/shipcontrails.h
	code/ship/shipfx.cpp
	code/ship/shipfx.h
	code/ship/shiphit.cpp
	code/ship/shiphit.h
	code/ship/subsysdamage.h
	code/sound/acm.cpp
	code/sound/acm.h
	code/sound/audiostr.cpp
	code/sound/audiostr.h
	code/sound/ds.cpp
	code/sound/ds.h
	code/sound/ds3d.cpp
	code/sound/ds3d.h
	code/sound/dscap.cpp
	code/sound/dscap.h
	code/sound/fsspeech.cpp
	code/sound/fsspeech.h
	code/sound/ogg/ogg.cpp
	code/sound/ogg/ogg.h
	code/sound/openal.cpp
	code/sound/openal.h
	code/sound/rtvoice.cpp
	code/sound/rtvoice.h
	code/sound/sound.cpp
	code/sound/sound.h
	code/sound/speech.cpp
	code/sound/speech.h
	code/sound/voicerec.cpp
	code/sound/voicerec.h
	code/species_defs/species_defs.cpp
	code/species_defs/species_defs.h
	code/starfield/nebula.cpp
	code/starfield/nebula.h
	code/starfield/starfield.cpp
	code/starfield/starfield.h
	code/starfield/supernova.cpp
	code/starfield/supernova.h
	code/stats/medals.cpp
	code/stats/medals.h
	code/stats/scoring.cpp
	code/stats/scoring.h
	code/stats/stats.cpp
	code/stats/stats.h
	code/tgautils/tgautils.cpp
	code/tgautils/tgautils.h
	code/ui/button.cpp
	code/ui/checkbox.cpp
	code/ui/gadget.cpp
	code/ui/icon.cpp
	code/ui/inputbox.cpp
	code/ui/keytrap.cpp
	code/ui/listbox.cpp
	code/ui/radio.cpp
	code/ui/scroll.cpp
	code/ui/slider.cpp
	code/ui/slider2.cpp
	code/ui/ui.h
	code/ui/uidefs.h
	code/ui/uidraw.cpp
	code/ui/uimouse.cpp
	code/ui/window.cpp
	code/weapon/beam.cpp
	code/weapon/beam.h
	code/weapon/corkscrew.cpp
	code/weapon/corkscrew.h
	code/weapon/emp.cpp
	code/weapon/emp.h
	code/weapon/flak.cpp
	code/weapon/flak.h
	code/weapon/muzzleflash.cpp
	code/weapon/muzzleflash.h
	code/weapon/shockwave.cpp
	code/weapon/shockwave.h
	code/weapon/swarm.cpp
	code/weapon/swarm.h
	code/weapon/trails.cpp
	code/weapon/trails.h
	code/weapon/weapon.h
	code/weapon/weapons.cpp
	# For "old" MSVC?
	#${CMAKE_CURRENT_SOURCE_DIR}/globalincs/fsmemory.cpp
	#${CMAKE_CURRENT_SOURCE_DIR}/globalincs/fsmemory.h
)

if(UNIX)
	list(APPEND libcode_SOURCES
		code/io/joy.h
		code/io/joy_ff.h
		code/io/joy-unix.cpp
		code/osapi/osapi_unix.cpp
		code/osapi/osapi.h
		code/osapi/osregistry_unix.cpp
		code/osapi/osregistry.h
		code/osapi/outwnd_unix.cpp
		code/osapi/outwnd.h
		code/windows_stub/stubs.cpp
		code/windows_stub/config.h
	)
elseif(MSVC)
	list(APPEND libcode_SOURCES
		code/directx/vasync.h
		code/directx/vd3dtypes.h
		code/directx/vddraw.h
		code/directx/vdinput.h
		code/directx/vdplay.h
		code/directx/vdplobby.h
		code/directx/vdsetup.h
		code/directx/vdvp.h
		code/globalincs/mspdb_callstack.cpp
		code/globalincs/mspdb_callstack.h
		code/globalincs/windebug.cpp
		code/graphics/gl/GLAUX.h
		code/graphics/gl/Glext.h
		code/graphics/gl/GLU.h
		code/graphics/gl/wglext.h
		code/graphics/gl/Gl.h
		code/io/joy.cpp
		code/io/joy_ff.cpp
		code/io/sw_error.hpp
		code/io/sw_force.h
		code/io/sw_guid.hpp
		code/io/swff_lib.cpp
		code/network/multi_update.cpp
		code/network/multi_update.h
		code/network/stand_gui.cpp
		code/osapi/monopub.h
		code/osapi/osapi.cpp
		code/osapi/osapi.h
		code/osapi/osregistry.cpp
		code/osapi/osregistry.h
		code/osapi/outwnd.cpp
		code/osapi/outwnd.h
	)
endif()

add_library(libcode OBJECT ${libcode_SOURCES})
