# Visual Studio

set_property(GLOBAL PROPERTY DEBUG_CONFIGURATIONS Debug Debug_SSE Debug_SSE2 Debug_AVX)

# Base
set(CMAKE_C_FLAGS "/MP /GS- /analyze- /Zc:wchar_t /errorReport:prompt /WX- /Zc:forScope /Gd /EHsc /nologo")
set(CMAKE_CXX_FLAGS "/MP  /GS- /analyze- /Zc:wchar_t /errorReport:prompt /WX- /Zc:forScope /Gd /EHsc /nologo")
set(CMAKE_EXE_LINKER_FLAGS "/MANIFEST /DYNAMICBASE:NO /MAPINFO:EXPORTS /SAFESEH:NO /MANIFESTUAC:NO /ERRORREPORT:PROMPT /NOLOGO")

# Release
set(CMAKE_C_FLAGS_RELEASE "/GL /W2 /Gy- /Zi /O2 /Ob2 /fp:fast /GF /Oy /Oi /MT")
set(CMAKE_CXX_FLAGS_RELEASE "/GL /W2 /Gy- /Zi /O2 /Ob2 /fp:fast /GF /Oy /Oi /MT")
set(CMAKE_EXE_LINKER_FLAGS_RELEASE "/LTCG /INCREMENTAL:NO /NODEFAULTLIB:libc.lib /NODEFAULTLIB:libcd.lib /NODEFAULTLIB:libci.lib")

# Release SSE
set(CMAKE_C_FLAGS_RELEASE_SSE "${CMAKE_C_FLAGS_RELEASE} /arch:SSE")
set(CMAKE_CXX_FLAGS_RELEASE_SSE "${CMAKE_CXX_FLAGS_RELEASE} /arch:SSE")
set(CMAKE_EXE_LINKER_FLAGS_RELEASE_SSE "${CMAKE_EXE_LINKER_FLAGS_RELEASE}")

# Release SSE2
set(CMAKE_C_FLAGS_RELEASE_SSE2 "${CMAKE_C_FLAGS_RELEASE} /arch:SSE2")
set(CMAKE_CXX_FLAGS_RELEASE_SSE2 "${CMAKE_CXX_FLAGS_RELEASE} /arch:SSE2")
set(CMAKE_EXE_LINKER_FLAGS_RELEASE_SSE2 "${CMAKE_EXE_LINKER_FLAGS_RELEASE}")

# Release AVX
set(CMAKE_C_FLAGS_RELEASE_AVX "${CMAKE_C_FLAGS_RELEASE} /arch:AVX")
set(CMAKE_CXX_FLAGS_RELEASE_AVX "${CMAKE_CXX_FLAGS_RELEASE} /arch:AVX")
set(CMAKE_EXE_LINKER_FLAGS_RELEASE_AVX "${CMAKE_EXE_LINKER_FLAGS_RELEASE}")

# Debug
set(CMAKE_C_FLAGS_DEBUG "/W4 /Gy /ZI /Od /RTC1 /Gd /Oy- /MTd")
set(CMAKE_CXX_FLAGS_DEBUG "/W4 /Gy /ZI /Od /RTC1 /Gd /Oy- /MTd")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG "/DEBUG /INCREMENTAL /NODEFAULTLIB:libc.lib /NODEFAULTLIB:libcd.lib /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:libci.lib")

# Debug SSE
set(CMAKE_C_FLAGS_DEBUG_SSE "${CMAKE_C_FLAGS_DEBUG} /arch:SSE")
set(CMAKE_CXX_FLAGS_DEBUG_SSE "${CMAKE_CXX_FLAGS_DEBUG} /arch:SSE")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG_SSE "${CMAKE_EXE_LINKER_FLAGS_DEBUG}")

# Debug SSE2
set(CMAKE_C_FLAGS_DEBUG_SSE2 "${CMAKE_C_FLAGS_DEBUG} /arch:SSE2")
set(CMAKE_CXX_FLAGS_DEBUG_SSE2 "${CMAKE_CXX_FLAGS_DEBUG} /arch:SSE2")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG_SSE2 "${CMAKE_EXE_LINKER_FLAGS_DEBUG}")

# Debug AVX
set(CMAKE_C_FLAGS_DEBUG_AVX "${CMAKE_C_FLAGS_DEBUG} /arch:AVX")
set(CMAKE_CXX_FLAGS_DEBUG_AVX "${CMAKE_CXX_FLAGS_DEBUG} /arch:AVX")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG_AVX "${CMAKE_EXE_LINKER_FLAGS_DEBUG}")